# Generated by Django 6.0.2 on 2026-02-24 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_security_and_mfa'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vote',
            name='unique_vote_per_voter_per_election',
        ),
    ]
