# Generated by Django 6.0.2 on 2026-02-24 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_remove_vote_unique_vote_per_voter_per_election'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('election', 'voter_hash'), name='unique_vote_per_voter_per_election'),
        ),
    ]
