# Generated by Django 6.0.2 on 2026-02-24 01:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_vote_unique_vote_per_voter_per_election'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='candidates_purged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='votes', to='voting.candidate'),
        ),
        migrations.CreateModel(
            name='ElectionResultSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_votes', models.PositiveIntegerField(default=0)),
                ('results_json', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('election', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result_snapshot', to='voting.election')),
            ],
        ),
    ]
