# Generated by Django 6.0.2 on 2026-02-24 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_election_candidates_purged_at_alter_vote_candidate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='access_password_hash',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='election',
            name='max_votes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
