# Generated by Django 4.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_election_candidates_purged_at_alter_vote_candidate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='voter_identifier',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='vote',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='electionresultsnapshot',
            name='encrypted_results',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='electionresultsnapshot',
            name='encryption_key',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
