# Generated by Django 4.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_add_encryption_and_anonymous_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='status',
            field=models.CharField(choices=[('registration', 'Registration'), ('open', 'Open'), ('closed', 'Closed')], default='registration', max_length=15),
        ),
        migrations.AddField(
            model_name='election',
            name='registration_starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='election',
            name='registration_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='election',
            name='voter_filter_pattern',
            field=models.CharField(blank=True, help_text='Optional: Filter voters by pattern in user identification or matric number (e.g., \'CS\', \'2021\', \'A\')', max_length=200),
        ),
        migrations.CreateModel(
            name='VoterRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_identification', models.CharField(max_length=120)),
                ('matric_number', models.CharField(max_length=50)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voter_registrations', to='voting.election')),
            ],
        ),
        migrations.AddConstraint(
            model_name='voterregistration',
            constraint=models.UniqueConstraint(fields=['election', 'user_identification'], name='unique_registration_per_user_per_election'),
        ),
    ]
