# Generated by Django 6.0.2 on 2026-02-24 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_election_access_password_hash_election_max_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminmfa',
            name='secret_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
