# Generated by Django 6.0.2 on 2026-02-24 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_adminmfa_secret_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminmfa',
            name='last_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
