# Generated by Django 4.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_add_registration_and_voter_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='election_group',
            field=models.CharField(blank=True, help_text='Optional: Group name for shared registration across multiple elections', max_length=100),
        ),
        migrations.AddField(
            model_name='voterregistration',
            name='election_group',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
