# Generated by Django 6.0.2 on 2026-03-12 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_adminmfa_last_verified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminmfa',
            name='failed_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adminmfa',
            name='last_failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminmfa',
            name='last_failed_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
