# Generated by Django 4.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_add_group_elections_and_fix_candidate_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voterregistration',
            old_name='candidate_id',
            new_name='user_id',
        ),
        migrations.AlterUniqueConstraint(
            name='unique_registration_per_candidate_per_election',
            constraint=models.UniqueConstraint(fields=['election', 'user_id'], name='unique_registration_per_user_per_election'),
            model='voterregistration',
        ),
    ]
