# Generated by Django 4.2.7

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('voting', '0009_change_to_user_id_and_add_ip_restriction'),
    ]

    operations = [
    ]
