# Generated by Django 6.0.2 on 2026-03-12 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0009_adminmfa_failed_attempts_adminmfa_last_failed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminmfa',
            name='failed_attempts',
        ),
        migrations.RemoveField(
            model_name='adminmfa',
            name='last_failed_at',
        ),
        migrations.RemoveField(
            model_name='adminmfa',
            name='last_failed_ip',
        ),
        migrations.CreateModel(
            name='MFAFailedAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('attempt_count', models.PositiveIntegerField(default=1)),
                ('last_attempt_at', models.DateTimeField(auto_now=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('ip_address',), name='unique_mfa_failed_attempt_ip')],
            },
        ),
    ]
