# Generated by Django 4.2.7

from django.db import migrations, models


def migrate_username_field(apps, schema_editor):
    """Populate username field from user_id or matric_number"""
    VoterRegistration = apps.get_model('voting', 'VoterRegistration')
    for registration in VoterRegistration.objects.all():
        # Use user_id if available, otherwise use matric_number
        registration.username = registration.user_id or registration.matric_number
        registration.save()

def reverse_migrate_username_field(apps, schema_editor):
    """Reverse data migration - this would be more complex in practice"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0010_add_user_ip_encryption'),
    ]

    operations = [
    ]
