# Generated by Django 6.0 on 2026-05-11 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0010_remove_adminmfa_failed_attempts_and_more'),
        ('voting', '0011_consolidate_to_username'),
    ]

    operations = [
    ]
