# Generated by Django 6.0 on 2026-05-11 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0012_merge_20260511_0314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voterregistration',
            name='user_identification',
        ),
        migrations.AlterField(
            model_name='election',
            name='voter_filter_pattern',
            field=models.CharField(blank=True, help_text="Optional: Filter voters by pattern in candidate ID or matric number (e.g., 'CS', '2021', 'A')", max_length=200),
        ),
    ]
